"""add_srs_and_flashcard_sets

Revision ID: 713f39fa8a87
Revises: d736618fb3a5
Create Date: 2025-08-16 12:28:07.000433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713f39fa8a87'
down_revision: Union[str, None] = 'd736618fb3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
