"""add_tags_column_to_notes_table

Revision ID: c297091e7da0
Revises: ff_add_user_plan
Create Date: 2025-08-28 13:36:09.974644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "c297091e7da0"
down_revision: Union[str, None] = "ff_add_user_plan"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes", sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes", "tags")
    # ### end Alembic commands ###
